language: node_js
cache:
    directories:
    - node_modules
sudo: false
addons:
    postgresql: "9.5"
before_script: psql -c 'create database uptime_test;' -U postgres
script: npm test --coverage
notifications:
    email: false