language: node_js
node_js:
- "0.12"
- "5.3"
cache:
    directories:
    - node_modules
sudo: false
addons:
    postgresql: "9.5"
before_script: psql -c 'create database uptime_test;' -U postgres
script: npm test --coverage
notifications:
    email: false